//
// education
export const OPEN_ADD_EDUCATION = 'OPEN_ADD_EDUCATION'
export const CLOSE_ADD_EDUCATION = 'CLOSE_ADD_EDUCATION'
export const OPEN_UPDATE_EDUCATION = 'OPEN_UPDATE_EDUCATION'
export const CLOSE_UPDATE_EDUCATION = 'CLOSE_UPDATE_EDUCATION'
export const OPEN_DELETE_EDUCATION = 'OPEN_DELETE_EDUCATION'
export const CLOSE_DELETE_EDUCATION = 'CLOSE_DELETE_EDUCATION'